# Generated by Django 3.2.13 on 2022-06-30 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_prettynum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prettynum',
            name='price',
            field=models.IntegerField(default=100, verbose_name='价格'),
        ),
    ]
